### ISSUE TITLE
Throw in promise-fulfillment swallows exception

### ISSUE THREAD

**Issue by johnjbarton** [kriskowal/q#30]
``` html
<html>
<head>
<script src="../../lib/q/q.js"></script>
<script>

// Accept a promise for load, and report the success or failure of the load
function foo(loaded) {
 return Q.when(
   loaded, 
   function glory(loaded){
     // Ooops the processing of success path fails!
     throw new Error("You lose");
     console.log("We have ", loaded);
   }, 
   function fail(err) {
     console.error("We have "+err);
   }
 );
};

// Create a promise for a load
function promiseLoaded() {
  var defer = Q.defer();
  window.addEventListener(
    'load', 
    function(event) {
      defer.resolve("success");
    }, 
    false
  );
  return defer.promise;
}

function main() {
  // foo returns a promise, but we don't look at the return so we lose.
  foo(promiseLoaded());
}

main();
</script>
</head>
<body>
<h1>Bad developer ergonomics: throw in promise fulfillment swallows exception</h1>
<p>May be related to <a href="https://github.com/kriskowal/q/issues/23">Issue 23 on github q</a>
</body>
</html>
```

**Comment by axelson** [comment]
@kriskowal is there a write-up on how to use `done()` to avoid "exception swallowing"?

**Comment by kriskowal** [comment]
@axelson https://github.com/kriskowal/q#the-end

**Comment by randallb** [comment]
So I love Q, and prefer it, except this error handling case is really difficult on me.

https://github.com/tildeio/rsvp.js/#error-handling

In RSVP, they have an "error" event that fires, meaning as a user you can have some `console.assert` thing show any unhandled errors. I'd love to have some way of surfacing all exceptions at least while developing... would this be something you'd be interested in having in Q? Even if as "Q.onError` if there's no native event bus. (I haven't yet looked at code.)

**Comment by randallb** [comment]
Ah it'll only catch errors if you use the `.done()` method. I was proposing trying to trigger some event handler whenever an error is caught in a promise chain.

**Comment by kriskowal** [comment]
@randallb Sorry, that went out too soon. It probably does not do what you want. Q.onerror gets called for unhandled rejections that would get rethrown. It does not report errors that have been caught but have not been handled. There is a limbo for errors, where they might be observed and handled in a future turn. In the trivial case:

```js
var rejected = Q.reject(new Error('boo'));
Q.delay(1000, function () {
    return rejected;
}).done();
```

This is too trivial a case. The problem will show up if you use promise queues or asynchronous iterators / readers, since the producer and the consumer operate independently.

```js
var reader = Reader([1, 2, 3, 4])
.map(function (value) {
    if (value % 2) throw new Error('how odd');
});

// later...
reader.next().catch(function (error) {
});
```

So while we could surface unhandled errors in the same event loop turn like RSVP, it would be noisy for legitimate cases.

I need to refresh my context, but there are ongoing plans to surface other events like, ondefer, onresolve, onreject, onhandle that would be able to drive an inspector that would show "pending deferred" promises and "rejected unhandled" promises for any given moment.

**Comment by n2liquid** [comment]
If Q

    * held weak references to all promises upon creation,
    * and strong references to all errors upon rejection,
    * and dropped those error references whenever they're successfuly handled by a `catch()` clause,

couldn't we implement a function that runs once per event loop and throws unhandled errors if their corresponding promise has been garbage collected?

Weak references to promises that have been garbage collected but have no outstanding unhandled errors are just dropped as well.

Since this comes at a performance cost and not every JavaScript engine Q runs on would necessarily support ES6's WeakMaps or whatever we use to implement this, this feature could just be disabled (either explicitly by client code or implicitly, if Q detects weak references aren't supported), and people who either don't want it or can't use it can just keep using `Q.done`.

Couldn't that work pretty well?

**Comment by domenic** [comment]
Yes, that would work wonderfully. Unfortunately weak maps are not weak references.

**Comment by n2liquid** [comment]
From https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap:

    Because of references being weak, WeakMap keys are not enumerable
    (i.e. there is no method giving you a list of the keys). If they were, the list
    would depend on the state of garbage collection, introducing non-determinism.
    If you want to have a list of keys, you should maintain it yourself.

Are you talking about this? It looks like you can kind of do it if you maintain a list of things that *should* be on the WeakMap, and check them periodically, no?

**Comment by domenic** [comment]
How would you maintain that list? (Answer: using a strong reference.)

**Comment by n2liquid** [comment]
True. How about adding unique IDs to promises and keeping a list of those, though?

**Comment by domenic** [comment]
How would you then find out if the promise is in the weak map?

**Comment by n2liquid** [comment]
Crap, true. They're not enumerable. That sucks :(

**Comment by kriskowal** [comment]
@n2liquid WeakMap is what it is for good reasons and is deliberately not for this use-case. There is a proposed WeakRef that provides a post mortem notification callback. We had to wait for TC39 to specify an event loop to get Promise. We’ll have to wait for TC39 to specify garbage collection before we’ll get WeakRef. Maybe we’ll get it someday, but that sounds hard. Members TC39 would prefer not to introduce a feature that would increase the observable differences between engines and specifying GC could seriously paint the language into a corner.

**Comment by n2liquid** [comment]
@kriskowal I see, it's a very tricky thing, indeed. But boy, I just don't feel safe that even things like TypeErrors would just be swallowed if I forget to use `Q.done` or yield the promise into a `Q.spawn` generator.

I guess dumping unhandled errors to the console before exiting the program is as good as it'll get for me (I'm not writing a server, so this is reasonable okay in this particular case).

**Comment by pacemkr** [comment]
```
// In browsers, uncaught exceptions are not fatal.
// Re-throw them asynchronously to avoid slow-downs.
```
https://github.com/kriskowal/q/blob/v1/q.js#L158

I'm sorry, but really?? This is all kinds of wrong. Not only are we swallowing exceptions, we're destroying the stack too. I don't know what the solution is, but this ain't it.

**Comment by n2liquid** [comment]
> I'm sorry, but really?? This is all kinds of wrong. Not only are we swallowing exceptions, we're destroying the stack too. I don't know what the solution is, but this ain't it.

I don't think rethrowing destroys the stack. The stack will be that of when the Error object was created.

**Comment by pacemkr** [comment]
`e.stack` is available (only sometimes, it seems) but as a string, which means I can't step up from it in the debugger and inspect values, etc.
