### ISSUE TITLE
Make `notify` return a promise derived from `onProgress` return values/throws.

### ISSUE THREAD

**Issue by domenic** [kriskowal/q#340]
See https://github.com/promises-aplus/progress-spec/issues/3#issuecomment-11609297. This would replace our current strategy of crashing if `onProgress` throws.

I believe it would be something along the lines of `Q.all(progressHandlers.map(Q.fcall))`.

**Comment by TimDaub** [comment]
![NOOOOOOOOOOOOOOOOOOOOOOOOOO](http://nontoxicrevolution.org/wp-content/uploads/2015/05/no-gif1.gif)

I'm trying to abort the hashing of a number of files and I'm using Q's promises to handle the async part.
So since this is never going to work in 1.0, I guess its not possible to stop the execution of a promise from the outside or is it?

**Comment by kriskowal** [comment]
@tomdaub cancellation is an unrelated concern to progress/notify. Q promises have multiple consumer semantics, so cancellation is tricky. I am contemplating building a library with a "task" primitive that is similar to a promise but with explicit fork() and cancel(), and @domenic is actively working out whether promises can become cancelable promises with reference counting on observers.

See: https://github.com/kriskowal/gtor
