### ISSUE TITLE
Logging consumed exceptions

### ISSUE THREAD

**Issue by aramk** [kriskowal/q#577]
This could be mentioned in several previous posts, and perhaps addressed in v2 but I wasn't able to find anything definitive. My concern is that when an exception is thrown in a deferred callback and it invokes the failure callback, there's no logging of the error when it's consumed.

Usually we use try/catch when we can indeed handle the exception, but not for catching syntax errors or undefined identifiers - things that are errors and should be plainly visible to the developer. Similarly for deferred callbacks, not having a failure callback means we get no feedback that our code has failed.

Is there a setting which allows logging of all consumed errors? This would be very useful for debugging the cause of failures without adding our own logging into every failure callback.

**Comment by jcalfee** [comment]
This is critical in my app.  It is getting to be very painful to grow the code base when there are hidden exceptions.  This is crippling my time by not being able to see these hidden errors.  I do not always have a clear point there I can call "done"...   I'm ready to patch the code, anything.  I just need it to log it, it does not have to change the flow of control.

**Comment by jcalfee** [comment]
Thanks for the patch!

**Comment by aramk** [comment]
@jcalfee I'm not entirely sure this is necessary anymore since discovering you actually need to call `.done()` after any `.then()` or `.fin()` calls to ensure exceptions are thrown - since you're making it clear no other callbacks will be used later in the code. It's an extra step but it's official way it seems.

**Comment by jcalfee** [comment]
I'm sure I will grow to love this architecture.  I would still suggest that a safeguard here is clearly needed to make the library a bit more friendly.  This is not a solution for use but perhaps a good example: In Java if an exception goes uncatched it makes it out of the `main` method.  The JVM does not ignore it, it gets logged.  Since this is standard, it is a very normal thing (good practice) to rely on that behaviour to report fatal exceptions that require user or programmer intervention.  It sounds like if one does not use `done` it is clearly an error so this should not be necessary.  By that logic though, compilers should not contain errors and programmers should just write the code without any errors the first time..

**Comment by kriskowal** [comment]
In Java (as in JavaScript) you catch and fail to log or rethrow, the error is consumed. That is not a fundamental difference.

However, there is a fundamental difference between synchronous exceptions and asynchronous exceptions. The promise *must* catch the exception so that it can be observed by *zero or more* consumers in the future. It is possible that nobody will care about the failure, possible for multiple branches of logic to depend upon a promise and observe the failure, and possible for the failure to be cached until someone comes around and depends on the promise eventually.

Because of all of these scenarios, logging every error at the throw site generates substantial noise. If you have a sufficiently advanced promise graph browser, as you would with a technology like Causeway or Zipkin but which is not yet in devtools for the web, it would be possible to inspect the state of every promise and their causal chains. Barring that, it would be useful to see a snapshot of all of the "pending" and "rejected but not yet handled" promises at any point in time. Logging every failure at the call site would make it possible to see every error, but manually poring over the logs to determine whether that error has been handled, how many times it has been handled, and whether it will ever be handled, is not a viable debugging technique.

**Comment by aramk** [comment]
Thanks @kriskowal for the detailed justification.
