### ISSUE TITLE
Context / bind

### ISSUE THREAD

**Issue by magalhas** [kriskowal/q#636]
Is there any feature similar to Bluebird `bind` on Q?

**Comment by benjamingr** [comment]
No, there is not.

**Comment by magalhas** [comment]
Are there any plans for it? Is a PR welcome?

**Comment by kriskowal** [comment]
Version 2 of Q has experimental support for passing a thisp as an argument to then. I do not intend to implement bind() because it leaks information downstream. This introduces a security hazard to the interface which, while perhaps unimportant to many users, it is important to discourage its use so that code written for promises remains portable to environments where safety is a concern.
