### ISSUE TITLE
deferred.resolve parameters

### ISSUE THREAD

**Issue by aadamsx** [kriskowal/q#662]
How many parameters can a deferred.resolve promise take?

It seems only one at a time... it would be great if I could do something like this:

deferred.resolve(file, data); // for example.
return deferred.promise;

**Comment by arikon** [comment]
@aadamsx You could use it like this:

```js
deffered.resolve([file.data]);

deffered.promise.spread(function(file, data) {
   // ...
});
```

**Comment by aadamsx** [comment]
Thanks @arikon, but what I ended up doing was just passing an object around like so:

var obj = {};
```
promiseFunction(obj)
.then(function (obj_returned) {
  var deferred = Q.defer();

  obj_returned.file = "filename.txt";
  obj_returned.datas = "data to write";

  deferred.resolve(obj_returned);
  return deferred.promise;
})
.then(function (obj_returned_again) {
   var deferred = Q.defer();
 
  // now I have both values
  var do_something = obj_returned_again.file;
  var do_something_else = obj_returned_again.datas;

  deferred.resolve();
  return deferred.promise;
})
.done();
```

**Comment by kriskowal** [comment]
There’s a bunch of writing on this topic, but in summary, a promise represents the return value or thrown error from a function call, either from the past or future. Since functions only return one value, you have to box and unbox multi-values as demonstrated above. Other designs run into strange complications.

I hope that the work-around above settles well with you.
