### ISSUE TITLE
Promises not adding to the array and returning values 

### ISSUE THREAD

**Issue by michaelpurnell** [kriskowal/q#718]
I'm trying to run a for loop that does a HTTP request, return values and then add the values into an array using promises but the values are not returning when i call the method getVenueID with .then.   It seems like the multiple promises are not being added to the array but dont know how to how to fix the issue. 

```
var rp = require('request-promise');
 var getVenueID = function (venueId){
      var addArray = [];
      for(var i = 0; i < venueId.length; i++){
              var deferred = Q.defer();
              var venueUrl  = 'https://www.eventbriteapi.com/v3/venues/'+ venueId[i].venue_id +'/?token=12345';

         rp(venueUrl).then(function(venue){
             deferred.resolve(venue);
             }).catch(function(err){
                deferred.reject(err);
            });
          addArray.push(deferred.promise);
      }
      return Q.all(addArray);
       }

  getVenueID(filteredData)
     .then(function(address){
              console.log(address );//should get the multiple object values here
      },
  function(err){
         console.log(err);
      }).done();
```

**Comment by kriskowal** [comment]
In the future, please address this kind of question to Stack Overflow. There is a very active community that can help diagnose these issues quickly.

The problem in this case is because each iteration of the for loop is overwriting the deferred variable, so deferred.resolve in a future turn of the event loop is only being called on the last iteration. The other promises remain pending forever. The problem can be solved by capturing the deferred in a closure for each iteration, or simply capturing the result of `rp` and adding it to the array, since the deferred is superfluous in this case.
