### ISSUE TITLE
.done() equivalent with native ES6 Promises?

### ISSUE THREAD

**Issue by dandv** [kriskowal/q#728]
I'm migrating a Chrome extension project that uses Q, to use native ES2015 Promises.

What should be done about `.done()`?

Replace with

```js
.catch(function catchException(error) {
  setTimeout(function () { throw error; }, 0);
});
```
[?](https://github.com/Zolmeister/promiz/issues/6#issuecomment-132285353)

**Comment by kriskowal** [comment]
That is certainly an option. You could also use [ASAP][] instead of setTimeout. You could also monkey patch that into `Promise.prototype.done`. Alternately, you could put your faith in the Chrome developer tools, which may even be automatically surfacing unhandled errors when promises get garbage collected.

[ASAP]: https://github.com/kriskowal/asap
