### ISSUE TITLE
Sync last version published between NPM and Bower

### ISSUE THREAD

**Issue by ThomasCrvsr** [kriskowal/q#742]
The last published version of Q on NPM is 1.4.1. When you install it with Bower, the version is 2.x. I just wonder if v2 is stable or is this a pre-release ? In the case of a pre-release, it might be relevant to tag it as pre-release no ?

**Comment by kriskowal** [comment]
2.x is pre-release. We do not maintain Bower’s packages. Not sure who does.

**Comment by mj1856** [comment]
Looks like Bower just pulls the git tags from the repo.

I think the issue is that Bower assumes [semver](http://semver.org/) guideline that pre-release versions are labeled, such as `2.0.0-beta`, and Q doesn't do that.

**Comment by mj1856** [comment]
FYI, [for nuget](https://www.nuget.org/packages/Q), I tagged the 2.x versions with `-expirimental`.  A nuget user would have to use the `-pre` flag to pull down a prerelease version.  I think to address this issue, it might make sense to re-tag the github repo similarly.

**Comment by ThomasCrvsr** [comment]
Yep, that's it @mj1856. It's would be also clearer and more obvious for devs when watching tags of the repo.

**Comment by kriskowal** [comment]
I should have used pre-release semver tags for the 2.0.0 train. Unfortunately, tags are not a mistake that can be unmade. Also, when the 2.x train is officially released, I don’t intend for it to replace the 1.x train as "latest" for a long time, possibly never, because there is a general expectation that `npm install q` will give you the version everyone is using, whereas `npm install q@2` opts in for the 2.x version ecosystem.

**Comment by ThomasCrvsr** [comment]
I close the issue as we agree on the problem, thanks for your answer :)
