### ISSUE TITLE
Q.all() behaviour vs. readme

### ISSUE THREAD

**Issue by philkunz** [kriskowal/q#749]
Hi, in the readme it states:

> The all function returns a promise for an array of values. When this promise is fulfilled, the array contains the fulfillment values of the original promises, in the same order as those promises. **If one of the given promises is rejected, the returned promise is immediately rejected**, not waiting for the rest of the batch. If you want to wait for all of the promises to either be fulfilled or rejected, you can use allSettled.

So in my unterstanding this should result in the second function getting called with "Hey,rejected" getting printed to console:
```javascript
var Q = require("q");

var deferred1 = Q.defer();
var deferred2 = Q.defer();

Q.all([deferred1,deferred2]).then(function(){
    console.log("Hey,resolved")
},function(){
    console.log("Hey,rejected")
});

deferred1.reject();
deferred2.resolve();
```
However using the code above the first function with "Hey resolved" gets called. Is this wanted?

**Comment by slushie** [comment]
You need to use `Q.all([deferred1.promise, deferred2.promise])...` here. 

Because `all()` takes an array of promises, any values that aren't promises (ie, the `deferred` objects) will be converted to promises. In this case, you are effectively calling `Q.all([Q(deferred1), Q(deferred2)])` which ends up resolved because all the values passed to `all()` are resolved.

**Comment by philkunz** [comment]
@slushie  True, sorry for my confusion there.
