### ISSUE TITLE
Q.timeout does not reject wrapped promise

### ISSUE THREAD

**Issue by danilotsr** [kriskowal/q#785]
See the following code example:

```
var Q = require('q');

var i = 0;
var DELAY = 100;

var loop = function() {
  console.log('loop', i++);
  return Q.delay(DELAY).then(loop);
};

var originalPromise = loop();
originalPromise
  .timeout(1000)
  .catch(
    function(error) {
      console.log(error, 'originalPromise', originalPromise.inspect());
    }
  );
```

Running this code would print

```
loop 0
loop 1
...
loop 9
[Error: Timed out after 1000 ms] 'originalPromise' { state: 'pending' }
loop 10
loop 11
... it would keep going on and on
```

There are two promise instances: `originalPromise` and the one returned by `.timeout(1000)`, let's call it `timeoutPromise`. This code runs fine in a sense that the promise chain would be interrupted after the set timeout of 1 second given that `timeoutPromise` would be rejected. However, the problem is that `originalPromise` isn't resolved, and it will never be resolved, therefore the loop keeps going on forever. Ideally, we would be able to inform `originalPromise` that it too should be rejected so that the loop can get interrupted.

**Comment by kriskowal** [comment]
This is behaving as designed. The timeout method (as with any other Q method) does not alter the state of the wrapped promise, which would constitute a plan interference hazard. Only the resolver has the power to reject the promise and the timeout method has no access to that capability. If you wish to be informed of the timeout, you must capture the timeout promise instead of the wrapped promise. This can be done by bringing the timeout into the loop around the work per iteration that must be accomplished in a timely fashion for the loop to continue.
