### ISSUE TITLE
Q.npost is not resolving promise

### ISSUE THREAD

**Issue by rvsx** [kriskowal/q#815]
Hi 

I am trying to execute the below code and Its not printing the logs inside npost.

var readFileFromDir = function readFileFrom(fileName){
    var deffered = Q.defer();
    fs.readFile(fileName, 'utf-8', function(err, data){
        if(err) {
            console.log('Failed to read', err);
            return deffered.reject(new Error(err));
        }
        console.log('successfully read');
        deffered.resolve(data);
    });
   return deffered.promise;
}

exports.readFileFromDir = readFileFromDir;

Q.npost(exports, "readFileFromDir", ['./index.js'])
    .then(function(data){
        console.log('Error while invoking-------------> Inside npost', err);
    })
    .catch(function(err){
        console.log('Successfully invoked ----------->Inside npost', data);
    })

output 
`successfully read`

Not sure why its not resolving the promise.

**Comment by Jabokoe** [comment]
Hello

Can you clarify for yourself why your code has an if-block for the error but no else block for logging success? In this case you are breaking the flow by returning in your if block. However otherwise you call `deffered.resolve`, which you are not returning. Instead you return your promise later, as expected but this makes your returning of deferred.reject less logical. The example for accessing filesystems with deffered has clearer control flow. Anyway assuming that part of the code is valid...

You have a .then stating a `data `argument but then try to use an undefined `err `and vice versa your .catch sais `err `but they you tried to use `data`. So you switched up success and failure. In the case of success your console will log "succesfully read" when actually executing that part but then it will try to read an undefined `err` while resolving the last bit of the promise, causing it to not even print the "invoking" message and no adittional data will be visible.

You can catch most kinds of undefined variable errors by using a [javascript linter](http://jslint.com/) and a "use strict" pragma. A lot of text editors or coding tools either have linters built in or plug-ins available.

PS: You can format your code as code with the backtick \` or by using the "Insert Code" button that has a **<>** Icon.
